### ISSUE TITLE
Red Dog for dreamcast

### ISSUE THREAD

**Issue by kevincrans** [OverSurge/PS1-Argonaut-Reverse#10]
@OverSurge Can u check if what's in this repository uses the same engine, it's open source by Argonaut developers, but only for dreamcast, so I don't know if it's this, BRender or something different.
https://github.com/mattgodbolt/reddog
It's MIT open-source, so anyone can use it without copyleft restriction.

**Comment by OverSurge** [comment]
Hi @kevincrans :wave:
I've quickly checked the repo and can't find big similarities with the PS1 Argonaut games I'm used to.

For examples, [the strategies](https://github.com/mattgodbolt/reddog/tree/main/dreamcast/reddog/game/strats) don't use the same syntax and have a different file extension as those in one Argonaut PS1 game I looked at.

There are some references to BRender in the repo : [example](https://github.com/mattgodbolt/reddog/blob/59144c5638940188c639b1e3e752c89a53e0d75d/dreamcast/reddog/game/render/quat.c#L197).

I can't say for sure if it's the same engine as the PS1 games, if it's BRender, or something else..
You should probably ask Matt Godbolt about that imo :)

**Comment by kevincrans** [comment]
Thanks!

**Comment by OverSurge** [comment]
@kevincrans Btw, here's a link to our Discord server dedicated to Argonaut PS1 games' reverse : [https://discord.gg/SDjkXx6JmU](https://discord.gg/SDjkXx6JmU)
Feel free to join :smile:
