### ISSUE TITLE
[PSX] - Alien Ressurection

### ISSUE THREAD

**Issue by OAleex** [OverSurge/PS1-Argonaut-Reverse#11]
Hello, congratulations on the reverse engineering and logic of the tool!
Any possibility in the future of it working on the PS1 Alien game?

**Comment by OverSurge** [comment]
Hi @OAleex :smiley:

Two years ago, I briefly spoke to 2 guys working on the reverse of this game.
From what I remember, the textures' format was similar to Harry Potter's one, but not quite the same.

I haven't done much more on this game than checking the textures tbh sorry :/
